Move mypy checks into bin/lint-python

diff --git a/bin/lint-python b/bin/lint-python
--- a/bin/lint-python
+++ b/bin/lint-python
@@ -18,8 +18,10 @@
 # define test binaries + versions
 FLAKE8_BUILD="flake8"
 MINIMUM_FLAKE8="3.5.0"
+MYPY_BUILD="mypy"
 PYCODESTYLE_BUILD="pycodestyle"
 MINIMUM_PYCODESTYLE="2.6.0"
+
 
 PYTHON_EXECUTABLE="python3"
 
@@ -55,6 +57,7 @@ function compile_python_test {
         exit "$COMPILE_STATUS"
     else
         echo "python compilation succeeded."
+        echo
     fi
 }
 
@@ -86,7 +89,8 @@ function pycodestyle_test {
     if [ $RUN_LOCAL_PYCODESTYLE == "False" ]; then
         # Get pycodestyle at runtime so that we don't rely on it being installed on the build server.
         # See: https://github.com/apache/spark/pull/1744#issuecomment-50982162
-        # Updated to the latest official version of pep8. pep8 is formally renamed to pycodestyle.  echo "downloading pycodestyle from $PYCODESTYLE_SCRIPT_REMOTE_PATH..."
+        # Updated to the latest official version of pep8. pep8 is formally renamed to pycodestyle.
+        echo "downloading pycodestyle from $PYCODESTYLE_SCRIPT_REMOTE_PATH..."
         if [ ! -e "$PYCODESTYLE_SCRIPT_PATH" ]; then
             curl --silent -o "$PYCODESTYLE_SCRIPT_PATH" "$PYCODESTYLE_SCRIPT_REMOTE_PATH"
             local curl_status="$?"
@@ -113,6 +117,31 @@ function pycodestyle_test {
         exit "$PYCODESTYLE_STATUS"
     else
         echo "pycodestyle checks passed."
+        echo
+    fi
+}
+
+function mypy_test {
+    local MYPY_REPORT=
+    local MYPY_STATUS=
+
+    if ! hash "$MYPY_BUILD" 2> /dev/null; then
+        echo "The $MYPY_BUILD command was not found. Skipping for now."
+        return
+    fi
+
+    echo "starting $MYPY_BUILD test..."
+    MYPY_REPORT=$( ($MYPY_BUILD --config-file bin/mypy.ini bin/repair) 2>&1)
+    MYPY_STATUS=$?
+
+    if [ "$MYPY_STATUS" -ne 0 ]; then
+        echo "mypy checks failed:"
+        echo "$MYPY_REPORT"
+        echo "$MYPY_STATUS"
+        exit "$MYPY_STATUS"
+    else
+        echo "mypy checks passed."
+        echo
     fi
 }
 
@@ -151,6 +180,7 @@ flake8 checks failed."
         exit "$FLAKE8_STATUS"
     else
         echo "flake8 checks passed."
+        echo
     fi
 }
 
@@ -164,5 +194,9 @@ PYTHON_SOURCE="$(find . -name "*.py")"
 compile_python_test "$PYTHON_SOURCE"
 pycodestyle_test "$PYTHON_SOURCE"
 flake8_test
+mypy_test
+
+echo
+echo "all lint-python tests passed!"
 
 popd &> /dev/null
